# Generated by Django 4.0.3 on 2022-04-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='name',
        ),
    ]
