# Generated by Django 4.0.3 on 2022-04-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_user_message_rename_room_message_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='room_name',
        ),
    ]
