# Generated by Django 4.0.3 on 2022-04-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_name_message_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='room_name',
        ),
    ]
